"""new fields in user model

Revision ID: 553ffb1197a4
Revises: 0d6d8544ed7e
Create Date: 2018-09-27 14:15:46.088000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '553ffb1197a4'
down_revision = '0d6d8544ed7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
